# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [ master ]

jobs:
  build:
    env:
      REF: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: grep
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: echo ${TITLE} | egrep "v[0-9]*\.[0-9]*\.[0-9]*" 
#     - name: Run failure script
#       if: failure()
#       run: exit 1
#     - name: Run success script
#       if: success()
#       run: exit 0
