# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    env:
      REF: ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: grep
      run: echo v-10.0.0 | egrep "v[0-9]*\.[0-9]*\.[0-9]*" 
    - name: Run failure script
      if: failure()
      run: |
        echo failure
    - name: Run success script
      if: success()
      run: |
        echo success
