name: Bump version
on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: actions/checkout@v2
      - name: tag
        run: |
          git tag v0.4.0
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
