name: Bump version
on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release-on-push:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        with:
          tag_name: ${{ toJson(github.event.pull_request.title) }}
          release_name: Release ${{ toJson(github.event.pull_request.title) }}
          body: ${{ toJson(github.event.pull_request.body) }} 
          draft: false
          prerelease: true
