name: Bump version
on: 
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release-on-push:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG: ${{ toJson(github.event.pull_request.title) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tag
        run: |
          echo ${TITLE}
          git tag ${TITLE} 
          git push origin ${TITLE}
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          BODY: ${{ toJson(github.event.pull_request.body) }} 
        with:
          tag_name: ${TAG}
          release_name: Release ${TAG}
          draft: false
          prerelease: false
